controller:
  state:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  base:
    type: smart_ros_controller/AllWheelSteeringController
    joints:
      wheel:
        front:
          - front_left_wheel_joint
          - front_right_wheel_joint
        middle:
          - middle_left_wheel_joint
          - middle_right_wheel_joint
        rear:
          - rear_left_wheel_joint
          - rear_right_wheel_joint
      steering:
        front:
          - front_left_wheel_steering_joint
          - front_right_wheel_steering_joint
        middle:
          - middle_left_wheel_steering_joint
          - middle_right_wheel_steering_joint
        rear:
          - rear_left_wheel_steering_joint
          - rear_right_wheel_steering_joint
    gains:
      - front_left_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - front_right_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - middle_left_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - middle_right_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - rear_left_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - rear_right_wheel_joint: {p: 10.0, i: 0.0, d: 1.0}
      - front_left_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
      - front_right_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
      - middle_left_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
      - middle_right_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
      - rear_left_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
      - rear_right_wheel_steering_joint: {p: 10.0, i: 0.0, d: 1.0}
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    wheel_track: 0.287
    wheel_base: 0.300
    wheel_radius: 0.035
